問題ありそうなファイルデータの削除
Caused by:
remote:        NameError: uninitialized constant Uglifier
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in load_missing_constant'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `load_missing_constant'
remote:        /tmp/build_0acd3f24/config/environments/production.rb:115:in `block in <main>'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.4/lib/rails/railtie.rb:216:in `instance_eval'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.4/lib/rails/railtie.rb:216:in `configure'
remote:        /tmp/build_0acd3f24/config/environments/production.rb:1:in `<main>'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.4/lib/rails/engine.rb:613:in `block (2 levels) in <class:Engine>'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.4/lib/rails/engine.rb:612:in `each'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.4/lib/rails/engine.rb:612:in `block in <class:Engine>'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `instance_exec'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `run'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:61:in `block in run_initializers'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:50:in `each'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:50:in `tsort_each_child'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:60:in `run_initializers'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.4/lib/rails/application.rb:363:in `initialize!'
remote:        /tmp/build_0acd3f24/config/environment.rb:5:in `<main>'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.4/lib/rails/application.rb:339:in `require_environment!'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.4/lib/rails/application.rb:523:in `block in run_tasks_blocks'
remote:        /tmp/build_0acd3f24/vendor/bundle/ruby/2.6.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/task.rb:61:in `block (2 levels) in define'
remote:        Tasks: TOP => environment
remote:        (See full trace by running task with --trace)
remote:
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote:
remote:  !     Push failed
remote:  !
remote:  ! ## Warning - The same version of this code has already been built: 1055514a35a52b4dad33e472fd68e3ceed2622d0
remote:  !
remote:  ! We have detected that you have triggered a build from source code with version 1055514a35a52b4dad33e472fd68e3ceed2622d0
remote:  ! at least twice. One common cause of this behavior is attempting to deploy code from a different branch.
remote:  !
remote:  ! If you are developing on a branch and deploying via git you must run:
remote:  !
remote:  !     git push heroku <branchname>:main
remote:  !
remote:  ! This article goes into details on the behavior:
remote:  !   https://devcenter.heroku.com/articles/duplicate-build-version
remote:
remote: Verifying deploy...
remote:
remote: !	Push rejected to shu28-origin-001.
remote:
To https://git.heroku.com/shu28-origin-001.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/shu28-origin-001.git'